/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cbr_malaria.user;

import cbr_malaria.admin.Lihat_Penyakit;
import cbr_malaria.model.Gejala;
import cbr_malaria.model.GejalaService;
import cbr_malaria.model.User;
import cbr_malaria.model.UserService;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Fauzy Wahyudi
 */
public class Konsultasi extends javax.swing.JFrame {

    Statement st;
    Connection con;
    ResultSet rs, rs2;
    String sql = "";
    String sql2 = "";
    GejalaService gejalaService;
    List<Gejala> gejalaList;
    UserService userService;
    List<User> userList;
    
    int noGejala;
    int maksGejala;
    String namaGejala;
    String openHtml = "<HTML><P style=\"text-align: justify \">";
    String closeHtml = "</P></HTML>";
    String apa = " Apakah anda merasa ";
    String tanya = " ?";
    String strJawaban = "";
    
    public static List<User> listUser;

    public Konsultasi(List<User> list) throws SQLException {
        initComponents();
        setTitle("Konsultasi");
        koneksiDB();
        gejalaService = new GejalaService(con);
        gejalaList = gejalaService.getAllGejala();
        maksGejala = gejalaService.getCountGejala();
        noGejala = 1;
        labelProses.setText(noGejala + " dari " + maksGejala + " Gejala");
        namaGejala = gejalaList.get(noGejala - 1).toString();
        labelGejala.setText(openHtml + apa + namaGejala + tanya + closeHtml);
        listUser = list;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        System.out.println("Data List Parsing =>"+listUser.get(0).toString());
    }

    public void koneksiDB() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/cbr_malaria", "root", "");
            st = con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Terhubung");
        }
    }

    public void nextIya() throws SQLException {
        if (noGejala == maksGejala) {
            try {
                strJawaban = strJawaban+","+noGejala;
                labelProses.setText("");
                labelGejala.setText("");
                String info[] = new String[1];
                info[0] = strJawaban;
                Hasil_Konsultasi.main(info, listUser);
                dispose();
            } catch (Exception e) {
                System.out.println(e);
                System.out.println("Error");
            }
        } else {
            if(strJawaban==null || strJawaban.equals("")){
                strJawaban = String.valueOf(noGejala);
            }else{
                strJawaban = strJawaban+","+noGejala;
            }
            
            noGejala = noGejala + 1;
            labelProses.setText(noGejala + " dari " + maksGejala + " Gejala");
            namaGejala = gejalaList.get(noGejala - 1).toString();
            labelGejala.setText(openHtml + apa + namaGejala + tanya + closeHtml);
        }
        System.out.println(strJawaban);

    }

    public void nextTidak() throws SQLException {
        if (noGejala == maksGejala) {
           try {
                labelProses.setText("");
                labelGejala.setText("");
                String info[] = new String[1];
                info[0] = strJawaban;
                Hasil_Konsultasi.main(info, listUser);
                dispose();
            } catch (Exception e) {
                System.out.println(e);
                System.out.println("Error");
            }
        } else {
            noGejala = noGejala + 1;
            labelProses.setText(noGejala + " dari " + maksGejala + " Gejala");
            namaGejala = gejalaList.get(noGejala - 1).toString();
            labelGejala.setText(openHtml + apa + namaGejala + tanya + closeHtml);
        }
        System.out.println(strJawaban);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelGejala = new javax.swing.JLabel();
        labelProses = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Konsultasi");

        labelGejala.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelGejala.setForeground(new java.awt.Color(255, 255, 255));
        labelGejala.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelGejala.setText("Apakah anda");

        labelProses.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelProses.setForeground(new java.awt.Color(255, 255, 255));
        labelProses.setText("1 dari 35 Gejala");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbr_malaria/assets/hapus.png"))); // NOI18N
        jButton1.setText("Tidak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 204, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cbr_malaria/assets/check.png"))); // NOI18N
        jButton2.setText("Iya");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelProses, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(347, 347, 347)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(170, 170, 170)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelGejala, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProses, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGejala, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            nextIya();
        } catch (SQLException ex) {
            Logger.getLogger(Konsultasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            nextTidak();
        } catch (SQLException ex) {
            Logger.getLogger(Konsultasi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(List<User> list) {
        /* Set the Nimbus look and feel */
        listUser = list;
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Konsultasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Konsultasi(listUser).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Konsultasi.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelGejala;
    private javax.swing.JLabel labelProses;
    // End of variables declaration//GEN-END:variables
}
